repos:
- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.2
  hooks:
    - id: prettier
      exclude_types:
        - "javascript"
        - "ts"
        - "scss"
        - "yaml"
        - "pem"
        - "html"
        - "svg"
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-merge-conflict
    - id: detect-private-key
    - id: trailing-whitespace
    - id: check-added-large-files
    - id: no-commit-to-branch
      args: [--branch, main]
