name: pre-commit
on: [push]
jobs:
  pre-commit:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 18
      - name: pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
      - uses: actions/setup-python@v4.7.1
        with:
          python-version: 3.10

